<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <CUE4ParseDir Condition="'$(CUE4ParseDir)' == ''">$(MSBuildThisFileDirectory)..\CUE4Parse\</CUE4ParseDir>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Twizzle.ImGui-Bundle.NET" Version="1.91.5.2" />
        <PackageReference Include="OpenTK" Version="4.9.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(CUE4ParseDir)CUE4Parse-Conversion\CUE4Parse-Conversion.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Shaders\**\*" />
        <None Remove="UI\Textures\*" />
        <None Remove="Rendering\Resources\*" />

        <EmbeddedResource Include="Shaders\**\*" />
        <EmbeddedResource Include="UI\Textures\*" />
        <EmbeddedResource Include="Rendering\Resources\*" />
    </ItemGroup>

</Project>
